swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /deposit/:
    get:
      tags:
      - deposit
      description: get Deposit
      operationId: DepositController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Deposit'
        "403":
          description: ""
    post:
      tags:
      - deposit
      description: create Deposit
      operationId: DepositController.Post
      parameters:
      - in: body
        name: body
        description: body for Deposit content
        required: true
        schema:
          $ref: '#/definitions/models.Deposit'
      responses:
        "201":
          description: '{int} models.Deposit'
        "403":
          description: body is empty
  /deposit/{id}:
    get:
      tags:
      - deposit
      description: get Deposit by id
      operationId: DepositController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Deposit'
        "403":
          description: :id is empty
    put:
      tags:
      - deposit
      description: update the Deposit
      operationId: DepositController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Deposit content
        required: true
        schema:
          $ref: '#/definitions/models.Deposit'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Deposit'
        "403":
          description: :id is not int
    delete:
      tags:
      - deposit
      description: delete the Deposit
      operationId: DepositController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /deposit/seed:
    get:
      tags:
      - deposit
      description: Seed deposits
      operationId: DepositController.Seed deposits
      responses:
        "200":
          description: '{string} seed success!'
        "403":
          description: error to seed
  /deposit/status/{id}:
    get:
      tags:
      - deposit
      description: Use to updade status
      operationId: DepositController.Update status deposit
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      responses:
        "200":
          description: '{string} updade status success!'
        "403":
          description: error updade status
definitions:
  models.Deposit:
    title: Deposit
    type: object
    properties:
      amount:
        type: number
        format: double
      createdAt:
        $ref: '#/definitions/models.Time'
      currency:
        type: string
      email:
        type: string
      id:
        type: integer
        format: int64
      status:
        type: string
      txid:
        type: string
      updatedAt:
        type: string
        format: datetime
  models.Time:
    title: Time
    type: string
tags:
- name: deposit
  description: |2
     DepositController operations for Deposit
